name: news_feed
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # For Icon
  flutter_launcher_icons: ^0.10.0

  # For Architecture
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^2.0.0-dev.9

  # For Networking
  http: ^0.13.5

  # For Model
  json_serializable: ^6.3.1
  freezed_annotation: ^2.1.0

  # For Image
  cached_network_image: ^3.2.1

  # Page Indicator
  smooth_page_indicator: ^1.0.0+2

  # WebView
  webview_flutter: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.2.0

  # For Model
  freezed: ^2.1.0+1

  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/ic_launcher.png"

  adaptive_icon_background: "#4CAF50"
  adaptive_icon_foreground: "assets/images/ic_launcher.png"

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Regular
      fonts:
        - asset: assets/fonts/KosugiMaru-Regular.ttf
    - family: Bold
      fonts:
        - asset: assets/fonts/NotoSansJP-Bold.otf
